version = 3.11.4
runner.dialect = scala3
maxColumn = 110
align.preset = none
docstrings.style = SpaceAsterisk
rewrite.rules = [RedundantBraces, RedundantParens]
rewrite.redundantBraces.stringInterpolation = true
trailingCommas = never
