import {themes as prismThemes} from 'prism-react-renderer';
import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

// This runs in Node.js — no browser APIs or JSX here.
//
// The documentation *content* is not authored here. Every guide page under `docs/` is generated by
// mdoc (`./mill docs.mdoc`) from the type-checked sources in `<repo>/docs/mdoc/`, then copied into
// `website/docs/` (git-ignored). A snippet that stops compiling breaks the docs build, by design.
// See CONTRIBUTING.md for the two-terminal dev loop.

const GITHUB = 'https://github.com/w0rxbend/scalacv';

const config: Config = {
  title: 'scalacv',
  tagline: 'A Scala 3 wrapper for the OpenCV 4.13 Java API',
  favicon: 'img/favicon.ico',

  future: {
    v4: true, // ease the eventual Docusaurus v4 upgrade
    // experimental_faster (Rspack) is enabled in a later, measured step — not by default.
  },

  url: 'https://w0rxbend.github.io',
  baseUrl: '/scalacv/',
  organizationName: 'w0rxbend',
  projectName: 'scalacv',

  // Free, thorough link checking at build time. `static/api/` (Scaladoc) is outside Docusaurus's
  // content graph and is NOT covered by these — a separate check guards those links (see CI).
  onBrokenLinks: 'throw',
  onBrokenAnchors: 'throw',
  markdown: {
    // `detect`: .md files parse as CommonMark, .mdx as MDX. The guide pages are generated from
    // mdoc as .md and are prose + fenced Scala — CommonMark renders bare `<:`, `=>`, `?=>`, `{ }`
    // literally, so the MDX-3 JSX-in-prose hazard never applies to them. Pages that need React
    // (Tabs) opt in explicitly by being authored as .mdx.
    format: 'detect',
    // Moved under markdown.hooks in 3.x (top-level is deprecated, removed in v4).
    hooks: {onBrokenMarkdownLinks: 'throw'},
  },

  // GitHub Pages serves `foo.html` at both `/foo` and `/foo/`. `false` makes Docusaurus emit
  // `foo.html` and link without the trailing slash, matching the canonical URL and avoiding the
  // redirect chain a mismatch would cause. Chosen deliberately (see DOCS-PLAN.md).
  trailingSlash: false,

  i18n: {defaultLocale: 'en', locales: ['en']},

  plugins: [
    // Local search via Pagefind: it indexes the final build/ HTML in a postBuild step — including
    // the static Scaladoc under /api/ that Algolia/other Docusaurus search can't reach — so ONE
    // ⌘K box covers guides AND the API reference. No account, works on PR previews. The chosen
    // fallback over Algolia DocSearch (needs an application, a live crawl, and lags deploys).
    // See SEARCH-REPORT.md.
    [
      'docusaurus-plugin-pagefind',
      {
        // Keep nav chrome out of the index; weight is left at Pagefind defaults (headings > body).
        excludeSelectors: ['.navbar', '.footer', '.theme-doc-toc-desktop', '.pagination-nav'],
      },
    ],
  ],

  presets: [
    [
      'classic',
      {
        docs: {
          // Docs-only mode: guides are served at the site root, matching the existing URL scheme
          // (`/scalacv/getting-started`, …) so inbound links survive the VitePress→Docusaurus move.
          routeBasePath: '/',
          sidebarPath: './sidebars.ts',
          // "Edit this page" must point at the mdoc SOURCE, never the generated copy in website/docs.
          // Generated basenames match their source 1:1, so this maps directly.
          editUrl: ({docPath}) => `${GITHUB}/edit/master/docs/mdoc/${docPath}`,
          showLastUpdateTime: true,
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    image: 'img/docusaurus-social-card.jpg',
    colorMode: {
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: 'scalacv',
      logo: {
        alt: 'scalacv',
        src: 'img/logo.svg',
        srcDark: 'img/logo-dark.svg',
      },
      items: [
        {type: 'docSidebar', sidebarId: 'docs', position: 'left', label: 'Docs'},
        // Guide `to:` links (Getting Started, Cookbook, …) and the Scaladoc API dropdown are added
        // in later migration steps, once those routes / static/api pages exist — onBrokenLinks:
        // 'throw' rejects any link whose target isn't present at build time.
        {href: GITHUB, label: 'GitHub', position: 'right'},
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'More',
          items: [{label: 'GitHub', href: GITHUB}],
        },
      ],
      copyright: 'Apache-2.0. Every Scala snippet on this site is type-checked by mdoc.',
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      // Prism's bundled Scala grammar predates Scala 3; the design step extends it via a
      // prism-include-languages swizzle. `bash`/`toml`/`diff` cover install snippets and diffs.
      additionalLanguages: ['java', 'scala', 'bash', 'toml', 'diff'],
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
