import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Typed, hand-ordered sidebar — deliberately NOT autogenerated, so ordering reflects user intent
// (Getting Started → high-level API → Memory & Resources → the OpenCV surface → detection →
// applications → concepts) rather than package/file layout. Every id here must exist as a
// generated page in website/docs after `./scripts/assemble-docs.sh` runs.
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Introduction',
      collapsed: false,
      items: [
        {type: 'doc', id: 'index', label: 'What is scalacv'},
        'getting-started',
        'architecture',
      ],
    },
    {
      type: 'category',
      label: 'The high-level API',
      items: ['image-api', 'graphics', 'cookbook'],
    },
    {
      // Hoisted near the top: this is the page that makes a native-memory library trustworthy.
      type: 'category',
      label: 'Memory & resources',
      items: ['mat-lifecycle', 'native-cache'],
    },
    {
      // Advanced operational topics — how to go fast, parallelise safely, and diagnose.
      type: 'category',
      label: 'Performance & scaling',
      items: ['performance', 'concurrency', 'testing', 'troubleshooting'],
    },
    {
      type: 'category',
      label: 'The OpenCV surface',
      items: [
        'image-io',
        'image-processing',
        'transforms',
        'color-masking',
        'filters',
        'drawing',
        'geometry',
        'contours',
        'hough',
      ],
    },
    {
      type: 'category',
      label: 'Detection & deep learning',
      items: [
        'object-detection',
        'face-recognition',
        'tracking',
        'motion-detection',
        'pose-estimation',
        'gestures',
        'dnn',
      ],
    },
    {
      type: 'category',
      label: 'Applications',
      items: ['conferencing', 'screen-analysis', 'ocr'],
    },
    {
      type: 'category',
      label: 'Robotics & 3D vision',
      items: ['calibration', 'navigation', 'marker-ar'],
    },
    {
      type: 'category',
      label: 'Video & runtime',
      items: ['video'],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: ['error-model', 'low-level'],
    },
    {
      type: 'category',
      label: 'Integrations',
      items: ['notebooks', 'zio'],
    },
  ],
};

export default sidebars;
