import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Typed, hand-ordered sidebar — deliberately NOT autogenerated, so ordering reflects user intent
// (Getting Started → high-level API → Memory & Resources → the OpenCV surface → detection →
// applications → concepts) rather than package/file layout. Every id here must exist as a
// generated page in website/docs after `./scripts/assemble-docs.sh` runs.
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Introduction',
      collapsed: false,
      items: [
        {type: 'doc', id: 'index', label: 'What is scalacv'},
        'getting-started',
        'basics',
        'architecture',
        'choosing',
      ],
    },
    {
      // Ordered by what each tutorial DEMANDS of the reader, not by topic. `sample-inputs` comes
      // first because the repository ships no bitmaps (a licensing decision), so three of the five
      // tutorials name a file the reader does not have; that page shows how to draw one. After it,
      // the two that run with no assets at all, then a clip, then a photo, then a model download.
      type: 'category',
      label: 'Tutorials',
      items: [
        'sample-inputs',
        'tutorial',
        'tutorial-color-tracking',
        'tutorial-video',
        'tutorial-faces',
        'tutorial-dnn',
      ],
    },
    {
      type: 'category',
      label: 'The high-level API',
      items: ['image-api', 'operations-reference', 'enums-reference', 'graphics', 'cookbook'],
    },
    {
      // Hoisted near the top: this is the page that makes a native-memory library trustworthy.
      type: 'category',
      label: 'Memory & resources',
      items: ['mat-lifecycle', 'native-cache'],
    },
    {
      // The production reading path, in order: measure it → read the numbers → parallelise it →
      // survive a producer faster than you → watch it → degrade instead of dying → test it →
      // ship it → diagnose it.
      //
      // Renamed from "Performance & scaling": the old label undersold the category and left
      // nowhere for an operational topic that is not about speed to land, so streaming,
      // observability and degradation had no home.
      //
      // `streaming-and-backpressure` could equally sit under "Video & runtime". It is here
      // deliberately — it is a capacity topic, and the reader who needs it arrives from
      // `concurrency`, not from `video`.
      type: 'category',
      label: 'Production',
      items: [
        'performance',
        'benchmark-results',
        'concurrency',
        'streaming-and-backpressure',
        'observability',
        'degradation-and-error-budgets',
        'testing',
        'deploying-to-production',
        'troubleshooting',
      ],
    },
    {
      type: 'category',
      label: 'The OpenCV surface',
      items: [
        'image-io',
        'image-processing',
        'transforms',
        'color-masking',
        'filters',
        'drawing',
        'geometry',
        'contours',
        'hough',
      ],
    },
    {
      type: 'category',
      label: 'Detection & deep learning',
      // `models` sits immediately before `dnn`: every page above it tells the reader to supply a
      // model file, and until that page existed none of them said where one comes from.
      items: [
        'object-detection',
        'face-recognition',
        'tracking',
        'motion-detection',
        'pose-estimation',
        'gestures',
        'models',
        'dnn',
      ],
    },
    {
      type: 'category',
      label: 'Applications',
      items: ['conferencing', 'screen-analysis', 'ocr'],
    },
    {
      type: 'category',
      label: 'Robotics & 3D vision',
      items: ['calibration', 'navigation', 'marker-ar'],
    },
    {
      type: 'category',
      label: 'Video & runtime',
      items: ['video'],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: ['glossary', 'opencv-java', 'faq', 'error-model', 'low-level'],
    },
    {
      type: 'category',
      label: 'Integrations',
      items: ['notebooks', 'zio'],
    },
  ],
};

export default sidebars;
