import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Typed, hand-ordered sidebar — deliberately NOT autogenerated, so ordering reflects user intent
// (Getting Started → Guides → Memory & Resources → Concepts → …) rather than package/file layout.
//
// This is the minimal foundation sidebar. The full guide tree is added when the mdoc pages are
// ported into website/docs (next migration step); doc IDs must exist before they can be listed
// here or the build fails.
const sidebars: SidebarsConfig = {
  docs: [
    {type: 'doc', id: 'index', label: 'What is scalacv'},
  ],
};

export default sidebars;
